[build]
builder = "nixpacks"

[deploy]
startCommand = "npm start"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "frontend"
sourceDir = "."
buildCommand = "npm run build"
startCommand = "npm start"
healthcheckPath = "/"
